<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pblica</name>
   <tag></tag>
   <elementGuidId>1df6cdb8-5194-4dd2-a2c9-0b4c44e72386</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.alert-radio-label.sc-ion-alert-md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='alert-input-5-0']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=radio[name=&quot;Pública&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>92d246dc-171a-47de-afe0-da35dc391ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert-radio-label sc-ion-alert-md</value>
      <webElementGuid>9e5b91ea-ef7e-40ad-8c1b-53e9a94be517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pública</value>
      <webElementGuid>53a13379-eac2-40d8-a734-3bc14f396ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert-input-5-0&quot;)/div[@class=&quot;alert-button-inner sc-ion-alert-md&quot;]/div[@class=&quot;alert-radio-label sc-ion-alert-md&quot;]</value>
      <webElementGuid>fd3a04fe-3d9e-429c-aacd-d01d6fdb6e72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='alert-input-5-0']/div/div[2]</value>
      <webElementGuid>e0b990f2-5d9a-41e5-ae29-b285f9179391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='perfil'])[1]/following::div[9]</value>
      <webElementGuid>ecd32aaa-cbeb-4f1b-85d0-8af7fa99f32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='armario'])[1]/following::div[9]</value>
      <webElementGuid>42f45185-4c8c-4071-9c55-93c49eee7387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privada'])[2]/preceding::div[3]</value>
      <webElementGuid>b350a857-ee57-464f-a23c-091a9ed33af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[5]</value>
      <webElementGuid>be507b97-8687-4a65-897c-134be173ecef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div[2]</value>
      <webElementGuid>0213179b-7b93-408a-a30a-c41ea9b817da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pública' or . = 'Pública')]</value>
      <webElementGuid>566369a1-5b95-4552-9e03-73a6e603b37b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
