<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pblica-ESS-aad-870</name>
   <tag></tag>
   <elementGuidId>3ec097e9-58af-4e5f-b0d1-2a026636e017</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-label > div.select-wrapper-inner > div.native-wrapper > div.select-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='select-label']/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select-label >> internal:text=&quot;Pública&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eb38151b-5156-41d8-a824-5a24af4a6108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e8be9fef-01ca-404d-bfc8-fde9c7544052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-text</value>
      <webElementGuid>8c457e51-6174-4b29-82c5-2865a7be0ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84ba5e73-e521-4326-b3df-95e47898815f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pública</value>
      <webElementGuid>ded9d367-823e-4a5b-ab60-df6b5574723e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/label[@id=&quot;select-label&quot;]/div[@class=&quot;select-wrapper-inner&quot;]/div[@class=&quot;native-wrapper&quot;]/div[@class=&quot;select-text&quot;]</value>
      <webElementGuid>68ffcb24-d4df-4c69-8bc1-6bc1f1a17479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NEW DRESS/ion-select_PblicaPrivada-W DRESS-aad</value>
      <webElementGuid>d8422450-a907-43d5-b6f4-8f2bb59f7e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>828b0c00-ff0f-48ca-a984-e8d353a4dec2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='select-label']/div[2]/div/div</value>
      <webElementGuid>89dfa611-f268-4e8d-8ccd-0a0b04428f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pública']/parent::*</value>
      <webElementGuid>8abf8f57-d101-45a8-a671-c3e1ca8d59f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pública' or . = 'Pública')]</value>
      <webElementGuid>0a88c30d-659f-4f88-ad8c-cf0b7a97fab8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
