<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Privada-ESS-aad-fbe</name>
   <tag></tag>
   <elementGuidId>a0065a25-a19a-4a90-b0ab-a64e0bc54579</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select-label > div.select-wrapper-inner > div.native-wrapper > div.select-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='select-label']/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select-label >> internal:text=&quot;Privada&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ae9da51-f6ec-4e62-a6bd-764c881b6f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4329a195-4af6-49a7-9cbf-87f51573db04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-text</value>
      <webElementGuid>5ce38f21-84b4-4a2a-a7a3-ce39bc432af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bed1f0fd-f326-41fd-858e-081b1ab51e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Privada</value>
      <webElementGuid>6610b0a2-7a01-4749-b385-25fa33e4ef28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/label[@id=&quot;select-label&quot;]/div[@class=&quot;select-wrapper-inner&quot;]/div[@class=&quot;native-wrapper&quot;]/div[@class=&quot;select-text&quot;]</value>
      <webElementGuid>f6bc8937-645d-4f6e-b13b-78cb2b11d7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NEW DRESS/ion-select_PblicaPrivada-W DRESS-aad</value>
      <webElementGuid>b36deb48-8ff0-4ee4-b82f-048a828244dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6a978561-9a82-4fd7-a933-969d4262e01c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='select-label']/div[2]/div/div</value>
      <webElementGuid>78270bba-dbe4-4de1-8983-debe7f8875e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Privada']/parent::*</value>
      <webElementGuid>f0fbeef6-c0ce-49f8-ad4d-302c5940f76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Privada' or . = 'Privada')]</value>
      <webElementGuid>87de0dac-d8eb-424a-a191-bbcf80ec8823</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
