<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Privada</name>
   <tag></tag>
   <elementGuidId>203d7693-3bef-4034-adf8-813301044455</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alert-input-4-1 > div.alert-button-inner.sc-ion-alert-md > div.alert-radio-label.sc-ion-alert-md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='alert-input-4-1']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=radio[name=&quot;Privada&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1724c4e5-6af1-42c4-a66b-ba628d463371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert-radio-label sc-ion-alert-md</value>
      <webElementGuid>bc73d20c-7756-4dc4-a18e-b1cbe24de476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Privada</value>
      <webElementGuid>54cffd79-4d25-4ea2-9dcc-7f7753097c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert-input-4-1&quot;)/div[@class=&quot;alert-button-inner sc-ion-alert-md&quot;]/div[@class=&quot;alert-radio-label sc-ion-alert-md&quot;]</value>
      <webElementGuid>31537a42-4400-4905-8bfd-06710581bf56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='alert-input-4-1']/div/div[2]</value>
      <webElementGuid>e3b3b4b4-c958-4cc1-a66c-21fa8e2817b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pública'])[2]/following::div[4]</value>
      <webElementGuid>336671fc-7fc5-4c38-b537-10c403b93118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='perfil'])[1]/following::div[13]</value>
      <webElementGuid>723123ed-ede3-4652-98ca-b6ba3ba4cb23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[1]</value>
      <webElementGuid>1bc7e6a2-c2d1-4500-aa99-0b5dc3cfafac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::div[1]</value>
      <webElementGuid>3f52877e-98fb-4be1-b473-aae1ad0838a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/div/div[2]</value>
      <webElementGuid>e6959286-551a-4daf-8207-42c0ecd1ba8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Privada' or . = 'Privada')]</value>
      <webElementGuid>61334215-aa95-49c7-adf9-e1c8b7f13d38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
