<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Action</name>
   <tag></tag>
   <elementGuidId>d618c571-9cf3-4747-a811-bf8022f462d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-alert[@id='ion-overlay-2']/div[2]/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.alert-button-group.sc-ion-alert-md</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>744ee2dd-4be9-4323-bdd7-2c97c02c186a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert-button-group sc-ion-alert-md</value>
      <webElementGuid>18441209-8c3a-4a3a-bf4f-9885fcceda0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Action</value>
      <webElementGuid>7517189a-ae55-490b-b317-01e50aa2d7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-overlay-2&quot;)/div[@class=&quot;alert-wrapper ion-overlay-wrapper sc-ion-alert-md&quot;]/div[@class=&quot;alert-button-group sc-ion-alert-md&quot;]</value>
      <webElementGuid>58d2de71-fec4-4006-b2f5-e2cb419a2346</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-alert[@id='ion-overlay-2']/div[2]/div[3]</value>
      <webElementGuid>6598c0d6-f227-49f8-b2c7-ce67f6fee55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email o Contraseña incorrectos'])[1]/following::div[2]</value>
      <webElementGuid>cab8f153-990d-419d-a955-5164da6c549f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrarse'])[1]/following::div[5]</value>
      <webElementGuid>5a0334a5-4730-4724-a0ac-4f4bbb307606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]</value>
      <webElementGuid>242deab9-f401-4c13-9ef0-5093cd865229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Action' or . = 'Action')]</value>
      <webElementGuid>0452f0e8-a8b5-441b-b3c6-f9603f88af74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
