<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-icon_exploracion_aperture-W DRESS-9f6</name>
   <tag></tag>
   <elementGuidId>c6b21adb-dfbe-4b7c-85b7-3ef4a53076eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ion-icon[name=&quot;aperture&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-icon[@name='aperture']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tab-button-carga ion-icon</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-icon</value>
      <webElementGuid>d3d01f09-c443-44d7-b819-33ca8bfd5521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aperture</value>
      <webElementGuid>6de79505-0788-4284-9f8c-461b8f4b7e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>aperture</value>
      <webElementGuid>462c1c33-5e00-4ac8-9e1f-a17841998bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6f2b5d84-5377-4423-8a36-b017de761a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md hydrated</value>
      <webElementGuid>3b72b551-ea01-4a08-a9ab-686d2c392dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-button-carga&quot;)/ion-icon[@class=&quot;md hydrated&quot;]</value>
      <webElementGuid>4f0cd561-94e4-475a-9482-5295ab124e49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ion-icon[@name='aperture']</value>
      <webElementGuid>768c4a7f-e4fc-473e-962c-9bbc7836104e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-tab-button[@id='tab-button-carga']/ion-icon</value>
      <webElementGuid>11b0f13e-814d-487b-80d0-8adb4dad0c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-tab-button[3]/ion-icon</value>
      <webElementGuid>99a90a74-e5be-4e26-a0ed-e2aebac810fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-icon[@name = 'aperture']</value>
      <webElementGuid>ac025d27-d35e-4e65-a356-9eef94df0a81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
