<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-col_20.28C</name>
   <tag></tag>
   <elementGuidId>20ed7ee1-d37c-47ad-80e6-60c6961dacce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-toolbar[@id='ion-toolbar']/ion-grid/ion-row/ion-col[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-col</value>
      <webElementGuid>7498df32-90ba-4e07-b44d-45a2c8d11355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md hydrated</value>
      <webElementGuid>ce92a67b-12c5-48b4-873c-ef8fd0d97589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20.28°C</value>
      <webElementGuid>f98f751f-b9d0-4b63-886d-c277845907e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-toolbar&quot;)/ion-grid[@class=&quot;md hydrated&quot;]/ion-row[@class=&quot;md hydrated&quot;]/ion-col[@class=&quot;md hydrated&quot;]</value>
      <webElementGuid>e93468b5-e8bc-4d40-9a31-a54b8c15ecd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-toolbar[@id='ion-toolbar']/ion-grid/ion-row/ion-col[4]</value>
      <webElementGuid>092ff2cd-4935-40c4-8270-64120f8cb894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrarse'])[1]/following::ion-col[4]</value>
      <webElementGuid>cff74f8d-7aeb-418e-9cf7-eab8c79a0eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INICIAR SESION'])[1]/following::ion-col[4]</value>
      <webElementGuid>64957e5a-38e0-48d4-922b-6fd5a51f3cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cielo claro'])[1]/preceding::ion-col[2]</value>
      <webElementGuid>3a88392f-bab3-4f0a-b113-6decf29c60f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='20.28°C']/parent::*</value>
      <webElementGuid>b8958800-a1da-4519-a959-dfd51df64aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-col[4]</value>
      <webElementGuid>5bed4e1a-93c3-4630-b558-d0e74124d915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-col[(text() = '20.28°C' or . = '20.28°C')]</value>
      <webElementGuid>09717540-319a-422a-a0e9-0f11e8cc71b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
