<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-select_PblicaPrivada-W DRESS-aad</name>
   <tag></tag>
   <elementGuidId>3c1726ff-8ee5-4466-842d-3e2fe35116b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ion-select[name=&quot;status&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-select[@name='status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;PúblicaPrivadaPública&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-select</value>
      <webElementGuid>6d2a9666-f4bb-47bb-8290-e1f326832ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>534e0ad3-ae27-4229-b08a-a6e666da9cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>4238f324-6452-4032-928c-d24d6c76dcce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>public</value>
      <webElementGuid>667c98dd-dde9-409e-9741-4ee4f3626278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid ion-untouched ion-pristine ion-valid md in-item has-value ion-focusable select-ltr select-label-placement-start hydrated</value>
      <webElementGuid>5cead15c-47f9-4ed2-86a3-790a6216db99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PúblicaPrivada</value>
      <webElementGuid>a130697f-49de-4517-be3f-588c283b2fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;plt-desktop md hydrated&quot;]/body[@class=&quot;backdrop-no-scroll&quot;]/app-root[1]/ion-app[@class=&quot;md ion-page hydrated&quot;]/ion-router-outlet[@class=&quot;hydrated&quot;]/app-barra[@class=&quot;ion-page can-go-back&quot;]/ion-tabs[1]/div[@class=&quot;tabs-inner&quot;]/ion-router-outlet[@class=&quot;hydrated&quot;]/app-carga[@class=&quot;ng-star-inserted ion-page&quot;]/ion-content[@class=&quot;md content-ltr hydrated&quot;]/ion-list[@class=&quot;md list-md hydrated&quot;]/ion-item[@class=&quot;item md item-lines-default item-control-needs-pointer-cursor in-list ion-activatable ion-focusable item-has-value ion-untouched ion-pristine ion-valid hydrated item-label item-label-floating ion-activated&quot;]/ion-select[@class=&quot;ng-untouched ng-pristine ng-valid ion-untouched ion-pristine ion-valid md in-item has-value ion-focusable select-ltr select-label-placement-start hydrated&quot;]</value>
      <webElementGuid>d5af9790-d793-4770-a6df-83332ab64589</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ion-select[@name='status']</value>
      <webElementGuid>52271ca5-624f-42c8-a50d-d8f3066caf26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-select</value>
      <webElementGuid>4dcf4850-0eba-4362-a749-ba5a2f71ee99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-select[@name = 'status' and (text() = 'PúblicaPrivada' or . = 'PúblicaPrivada')]</value>
      <webElementGuid>cd103b21-bf89-498e-875a-0abac30fde5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
