<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-icon_exploracion_search-W DRESS-fae</name>
   <tag></tag>
   <elementGuidId>2b7c14df-ffbd-476b-8528-45fcdfdb16d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ion-icon[name=&quot;search&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-icon[@name='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tab-button-exploracion ion-icon</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-icon</value>
      <webElementGuid>18fd848c-d55f-4f6e-856a-56e4196002f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>436ff07c-6457-4f12-bd4f-8d5d508f3449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>c17f9ccf-a059-4873-ab11-5a3ee7a401bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d2935907-0cb0-4d16-965d-9aa0d10ca2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md hydrated</value>
      <webElementGuid>2902649f-06a8-446b-93ae-976e15a1d50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-button-exploracion&quot;)/ion-icon[@class=&quot;md hydrated&quot;]</value>
      <webElementGuid>f0b98777-ee2b-4dd3-8d1c-86c020d9d4d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ion-icon[@name='search']</value>
      <webElementGuid>cb5724af-51af-4318-ae58-e6629ea006b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-tab-button[@id='tab-button-exploracion']/ion-icon</value>
      <webElementGuid>95e792b5-b81a-4ce9-b656-d6333b0b66f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-tab-button[2]/ion-icon</value>
      <webElementGuid>6eb33ed3-b01b-47ad-99eb-a62b8db3e437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-icon[@name = 'search']</value>
      <webElementGuid>653d4578-1666-4135-9b8d-8f2ca4dd0b3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
