<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-tab-button_exploracion-W DRESS-5b3</name>
   <tag></tag>
   <elementGuidId>ab13c9b7-7d36-41dd-9231-580f92449776</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-button-exploracion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-tab-button[@id='tab-button-exploracion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;exploracion&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-tab-button</value>
      <webElementGuid>54299c94-13f6-4e6a-b3ee-346b3e35cb70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tab</name>
      <type>Main</type>
      <value>exploracion</value>
      <webElementGuid>0f5bfacb-d729-4ad2-9a6b-588a3def3616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-tab</name>
      <type>Main</type>
      <value>exploracion</value>
      <webElementGuid>90ea836a-30c2-4035-8b9c-b0a7dba318e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-button-exploracion</value>
      <webElementGuid>8112d979-f39c-42b1-977e-c20c5953d98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md tab-has-icon tab-has-icon-only tab-layout-icon-top ion-activatable ion-selectable ion-focusable hydrated ion-activated</value>
      <webElementGuid>276ee25c-b6d8-4129-919e-03c074059887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> exploracion </value>
      <webElementGuid>88a5d93e-488d-45f1-82bc-f012fa829754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-button-exploracion&quot;)</value>
      <webElementGuid>b35418f6-e796-4e6b-9007-70a04ea4e8e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ion-tab-button[@id='tab-button-exploracion']</value>
      <webElementGuid>c74c0a72-f708-4779-a8a7-acfee9281717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='inicio'])[1]/following::ion-tab-button[1]</value>
      <webElementGuid>a977634a-2b6b-4c19-bf78-8db264d0b844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subir'])[1]/following::ion-tab-button[2]</value>
      <webElementGuid>5aff5a66-b711-4b8e-b2ba-fc2af5fe6682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='armario'])[1]/preceding::ion-tab-button[2]</value>
      <webElementGuid>8bd1a8c5-9e6c-4585-a153-addf1538d9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='perfil'])[1]/preceding::ion-tab-button[3]</value>
      <webElementGuid>206a1116-134d-4c29-a665-793ad627daec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='exploracion']/parent::*</value>
      <webElementGuid>5b1ffc42-d949-4c39-92e9-9e918be1b5da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-tab-button[2]</value>
      <webElementGuid>dc154f25-d61a-47c6-8224-dc570c9f250f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-tab-button[@id = 'tab-button-exploracion' and (text() = ' exploracion ' or . = ' exploracion ')]</value>
      <webElementGuid>288854af-4eab-4c4d-8c56-0ebea250199b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
